version: "3"
name: hadith-web-dev
services:
  database:
    extends:
      file: ../compose.yml
      service: database

  db_admin:
    extends:
      file: ../compose.yml
      service: db_admin

  cache:
    extends:
      file: ../compose.yml
      service: cache

  directus:
    extends:
      file: ../compose.yml
      service: directus
    depends_on:
      - cache
      - database

  nextjs:
    extends:
      file: ../compose.yml
      service: hadith-nextjs
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
      - ../../prisma:/app/prisma
    depends_on:
      - directus
