version: "3"
services:
  database:
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  cache:
    image: redis:6

  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    restart: always
    volumes:
      # Reuired only when using sqlite3
      # - ./data/database:/directus/database
      - ./data/uploads:/directus/uploads
      - ./data/directus-snapshots:/directus/snapshots
      - ./data/directus-extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      DB_CLIENT: "pg"
      # DB_FILENAME: "/directus/database/data.db"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      KEY: "sdfgasdkgfsdglfgdsakfgkjdsgfjlksdkj"
      SECRET: "efkhkwehfkjhwekjhfkjwehfkjhewkfwek"
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      # WEBSOCKETS_ENABLED: true
      CACHE_ENABLED: "true"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    depends_on:
      - directus
    restart: always
    ports:
      - 3000:3000
      - 6006:6006
