-- AlterTable
ALTER TABLE "Book" ALTER COLUMN "userCreated" SET DATA TYPE TEXT,
ALTER COLUMN "userUpdated" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Hadith" ALTER COLUMN "userCreated" SET DATA TYPE TEXT,
ALTER COLUMN "userUpdated" SET DATA TYPE TEXT;
